Repository kubernetes-csi/cluster-driver-registrar, pull requests merged in 2018-12, with the labels that each got.

#4 Auto-detect AttachRequired
  cmd/cluster-driver-registrar/k8s_register.go
  cmd/cluster-driver-registrar/main.go
  pkg/connection/connection.go
  pkg/connection/connection_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#9 Add msau42 to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10 Add more details about cluster-driver-registrar
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#12 Fix fmt issue in connection_test
  pkg/connection/connection_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
