Repository kubernetes-csi/cluster-driver-registrar, pull requests merged in 2019-01, with the labels that each got.

#14 Fix markdown error
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#15 removed redundant check and code cleanup
  cmd/cluster-driver-registrar/k8s_register.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#19 Add RBAC rules for CSI csidrivers CRD
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#20 Update usage and deployment documentation
  README.md
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#22 release tools
  .travis.yml
  Dockerfile
  Makefile
  cmd/csi-cluster-driver-registrar/k8s_register.go
  cmd/csi-cluster-driver-registrar/main.go
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/build.make
  release-tools/code-of-conduct.md
  release-tools/travis.yml
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#24 Migrate to k8s.io/klog from glog.
  Gopkg.lock
  Gopkg.toml
  cmd/csi-cluster-driver-registrar/k8s_register.go
  cmd/csi-cluster-driver-registrar/main.go
  pkg/connection/connection.go
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#21 [release-1.0] Update usage and deployment documentation
  README.md
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
