Repository kubernetes-csi/cluster-driver-registrar, pull requests merged in 2019-02, with the labels that each got.

#16 remove IDE specific files from .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/M

#25 Minor README updates
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#26 Bring README in line with master version.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#27 Update compatibility matrix to only reflect branch head
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 Cherrypick #27: Update compatibility matrix to only reflect branch head
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#29 Initialize flags first.
  cmd/csi-cluster-driver-registrar/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#31 update owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#32 use CSI connection lib
  Gopkg.lock
  Gopkg.toml
  cmd/csi-cluster-driver-registrar/main.go
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/release-tools/LICENSE
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/csi-api/pkg/crd/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#33 Remove unused code
  pkg/connection/connection.go
  pkg/connection/connection_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#34 Minor RBAC update
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Use GetDriverName from csi-lib-utils
  Gopkg.lock
  Gopkg.toml
  cmd/csi-cluster-driver-registrar/main.go
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/github.com/kubernetes-csi/csi-test/LICENSE
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.mock.go
  vendor/github.com/kubernetes-csi/csi-test/driver/mock.go
  vendor/github.com/kubernetes-csi/csi-test/mock/AUTHORS
  vendor/github.com/kubernetes-csi/csi-test/utils/grpcutil.go
  vendor/github.com/kubernetes-csi/csi-test/utils/safegoroutinetester.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/serverreflection.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
